export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  mode: 'Remote' | 'Hybrid' | 'Onsite';
  experience: 'Fresher' | '0-1' | '1-3' | '3-5' | '5+';
  skills: string[];
  source: 'LinkedIn' | 'Naukri' | 'Indeed';
  postedDaysAgo: number;
  salaryRange: string;
  applyUrl: string;
  description: string;
}

export const jobsData: Job[] = [
  {
    id: 'job-001',
    title: 'Junior Backend Developer',
    company: 'Infosys',
    location: 'Bengaluru',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'Spring Boot', 'MySQL', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://infosys.com/careers/job-001',
    description: 'We are looking for a Junior Backend Developer to join our growing team. You will work on building scalable REST APIs using Java and Spring Boot. This is a great opportunity to work with experienced engineers and learn enterprise development practices. You will be responsible for writing clean, testable code and contributing to architectural decisions.'
  },
  {
    id: 'job-002',
    title: 'React Developer (1-3 years)',
    company: 'Amazon',
    location: 'Hyderabad',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'JavaScript', 'CSS', 'Redux', 'TypeScript'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '12–18 LPA',
    applyUrl: 'https://amazon.com/careers/job-002',
    description: 'Join Amazon\'s frontend team to build next-generation user interfaces for millions of customers worldwide. We are seeking a React Developer with 1-3 years of experience to develop and maintain high-performance web applications. You will collaborate with product managers and designers to translate requirements into seamless user experiences using modern React patterns.'
  },
  {
    id: 'job-003',
    title: 'SDE Intern',
    company: 'Flipkart',
    location: 'Bengaluru',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['Python', 'JavaScript', 'SQL', 'Git'],
    source: 'Naukri',
    postedDaysAgo: 0,
    salaryRange: '₹20k–₹35k/month Internship',
    applyUrl: 'https://flipkart.com/careers/internship-001',
    description: 'Flipkart is hiring SDE interns for our summer program. You will work on real projects with mentorship from senior engineers. Responsibilities include writing clean code, participating in code reviews, and learning industry best practices. This is a paid internship with potential for full-time conversion based on performance.'
  },
  {
    id: 'job-004',
    title: 'QA Intern',
    company: 'TCS',
    location: 'Pune',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Selenium', 'Java', 'TestNG', 'SQL'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '₹15k–₹25k/month Internship',
    applyUrl: 'https://tcs.com/careers/qa-intern-001',
    description: 'TCS is seeking QA interns to join our quality assurance team. You will write automated test scripts using Selenium and Java, execute manual test cases, and report bugs. This internship provides hands-on experience with real testing frameworks and methodologies used in enterprise environments.'
  },
  {
    id: 'job-005',
    title: 'Graduate Engineer Trainee',
    company: 'Wipro',
    location: 'Noida',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'SQL', 'C++', 'Data Structures'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://wipro.com/careers/graduate-trainee-001',
    description: 'Wipro\'s Graduate Engineer Trainee program is designed for freshers. You will undergo comprehensive training in enterprise technologies, software development practices, and industry standards. After successful completion, you will be placed in project teams to contribute to real client projects with support from experienced mentors.'
  },
  {
    id: 'job-006',
    title: 'Frontend Intern',
    company: 'Zoho',
    location: 'Chennai',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    source: 'Naukri',
    postedDaysAgo: 2,
    salaryRange: '₹18k–₹32k/month Internship',
    applyUrl: 'https://zoho.com/careers/frontend-intern-001',
    description: 'Zoho is hiring frontend interns to build beautiful, responsive user interfaces. You will work with HTML, CSS, JavaScript, and React to create engaging web experiences. Our internship program offers real-world experience, mentorship, and exposure to modern frontend development practices.'
  },
  {
    id: 'job-007',
    title: 'Java Developer (0-1 years)',
    company: 'Accenture',
    location: 'Gurgaon',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'OOP', 'Maven', 'JUnit', 'SQL'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '5–8 LPA',
    applyUrl: 'https://accenture.com/careers/java-dev-001',
    description: 'Accenture is seeking fresh Java developers to join our development team. You will be involved in designing and implementing Java-based applications. We are looking for candidates with strong OOP concepts, understanding of design patterns, and enthusiasm to learn enterprise development. You will work on client projects with guided support.'
  },
  {
    id: 'job-008',
    title: 'Data Analyst Intern',
    company: 'Razorpay',
    location: 'Bengaluru',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'Tableau', 'Excel'],
    source: 'Indeed',
    postedDaysAgo: 1,
    salaryRange: '₹22k–₹38k/month Internship',
    applyUrl: 'https://razorpay.com/careers/analyst-intern-001',
    description: 'Razorpay is hiring data analyst interns to support our analytics team. You will analyze transaction data, create visualizations, and generate insights. You will work with SQL, Python, and Tableau to process and present data. This internship is perfect for candidates interested in data-driven decision making.'
  },
  {
    id: 'job-009',
    title: 'Python Developer (1-3 years)',
    company: 'Cognizant',
    location: 'Pune',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Python', 'Django', 'REST APIs', 'PostgreSQL'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '8–12 LPA',
    applyUrl: 'https://cognizant.com/careers/python-dev-001',
    description: 'Cognizant is looking for Python developers with 1-3 years of experience. You will develop backend services using Django and PostgreSQL. You will participate in the full software development lifecycle, including design, development, testing, and deployment of applications for our clients.'
  },
  {
    id: 'job-010',
    title: 'React Developer (0-1 years)',
    company: 'Freshworks',
    location: 'Chennai',
    mode: 'Remote',
    experience: '0-1',
    skills: ['React', 'JavaScript', 'CSS', 'Git', 'REST APIs'],
    source: 'Naukri',
    postedDaysAgo: 3,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://freshworks.com/careers/react-dev-001',
    description: 'Freshworks is seeking React developers to build customer communication software. You will work with modern React patterns, state management, and CSS-in-JS. We provide mentorship and focus on code quality. This is a great opportunity to work on products used by millions of businesses worldwide.'
  },
  {
    id: 'job-011',
    title: 'Backend Engineer (3-5 years)',
    company: 'Swiggy',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '3-5',
    skills: ['Go', 'Microservices', 'Kafka', 'Docker', 'AWS'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '15–22 LPA',
    applyUrl: 'https://swiggy.com/careers/backend-eng-001',
    description: 'Swiggy is hiring experienced backend engineers to scale our food delivery platform. You will design and build microservices in Go, work with Kafka for event streaming, and deploy on AWS. You will lead technical initiatives and mentor junior engineers while handling millions of transactions daily.'
  },
  {
    id: 'job-012',
    title: 'Full Stack Developer (1-3 years)',
    company: 'PhonePe',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'AWS'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '10–16 LPA',
    applyUrl: 'https://phonepe.com/careers/fullstack-001',
    description: 'PhonePe is seeking full stack developers to work on fintech products. You will develop user-facing features using React and backend services with Node.js. You will collaborate with product teams to ship features that impact millions of users in the Indian digital payment ecosystem.'
  },
  {
    id: 'job-013',
    title: 'QA Automation Engineer (1-3 years)',
    company: 'Capgemini',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Selenium', 'Java', 'TestNG', 'CI/CD'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '7–11 LPA',
    applyUrl: 'https://capgemini.com/careers/qa-automation-001',
    description: 'Capgemini is hiring QA automation engineers to ensure product quality. You will write automated test scripts, set up CI/CD pipelines, and collaborate with development teams. You will work on enterprise applications for global clients and contribute to quality improvement initiatives.'
  },
  {
    id: 'job-014',
    title: 'DevOps Engineer (3-5 years)',
    company: 'IBM',
    location: 'Pune',
    mode: 'Hybrid',
    experience: '3-5',
    skills: ['Kubernetes', 'Docker', 'Jenkins', 'AWS', 'Linux'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '14–20 LPA',
    applyUrl: 'https://ibm.com/careers/devops-eng-001',
    description: 'IBM is seeking DevOps engineers to manage cloud infrastructure at scale. You will work with Kubernetes, Docker, and Jenkins to automate deployment pipelines. You will monitor system performance, implement security best practices, and support global teams in cloud operations.'
  },
  {
    id: 'job-015',
    title: 'Frontend Developer (0-1 years)',
    company: 'Paytm',
    location: 'Delhi',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Redux'],
    source: 'Naukri',
    postedDaysAgo: 3,
    salaryRange: '5–8 LPA',
    applyUrl: 'https://paytm.com/careers/frontend-001',
    description: 'Paytm is hiring junior frontend developers to build digital payment experiences. You will work with React to create responsive, user-friendly interfaces. You will collaborate with designers and backend engineers to deliver high-quality products used by millions of Indians.'
  },
  {
    id: 'job-016',
    title: 'Machine Learning Engineer (1-3 years)',
    company: 'CRED',
    location: 'Bengaluru',
    mode: 'Remote',
    experience: '1-3',
    skills: ['Python', 'TensorFlow', 'Pandas', 'Scikit-learn', 'SQL'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '12–18 LPA',
    applyUrl: 'https://cred.club/careers/ml-engineer-001',
    description: 'CRED is hiring ML engineers to build intelligent fintech solutions. You will develop machine learning models for credit risk assessment and fraud detection. You will work with Python, TensorFlow, and large datasets to create production-ready ML pipelines.'
  },
  {
    id: 'job-017',
    title: 'Senior Backend Developer (5+ years)',
    company: 'Oracle',
    location: 'Hyderabad',
    mode: 'Hybrid',
    experience: '5+',
    skills: ['Java', 'Spring', 'Microservices', 'AWS', 'Docker'],
    source: 'LinkedIn',
    postedDaysAgo: 7,
    salaryRange: '20–28 LPA',
    applyUrl: 'https://oracle.com/careers/backend-senior-001',
    description: 'Oracle is seeking senior backend developers to lead architectural initiatives. You will design scalable microservices, mentor junior engineers, and drive technical excellence. You will work on global products used by enterprise customers worldwide.'
  },
  {
    id: 'job-018',
    title: 'UI/UX Designer (1-3 years)',
    company: 'Juspay',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Figma', 'User Research', 'Prototyping', 'CSS'],
    source: 'Indeed',
    postedDaysAgo: 2,
    salaryRange: '8–12 LPA',
    applyUrl: 'https://juspay.com/careers/designer-001',
    description: 'Juspay is hiring UI/UX designers to create beautiful payment interfaces. You will conduct user research, create prototypes, and iterate based on feedback. You will collaborate with engineers and product managers to deliver delightful user experiences for fintech products.'
  },
  {
    id: 'job-019',
    title: 'Data Analyst (0-1 years)',
    company: 'SAP',
    location: 'Delhi',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['SQL', 'Excel', 'Tableau', 'Python', 'Statistics'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '6–9 LPA',
    applyUrl: 'https://sap.com/careers/analyst-001',
    description: 'SAP is seeking data analysts to support business intelligence initiatives. You will analyze enterprise data, create dashboards, and provide actionable insights. You will work with SQL and Tableau to visualize complex datasets for stakeholders across the organization.'
  },
  {
    id: 'job-020',
    title: 'API Developer (1-3 years)',
    company: 'Dell',
    location: 'Hyderabad',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['REST APIs', 'Node.js', 'MongoDB', 'AWS', 'GraphQL'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '9–14 LPA',
    applyUrl: 'https://dell.com/careers/api-dev-001',
    description: 'Dell is hiring API developers to build scalable backend services. You will design and implement REST and GraphQL APIs using Node.js. You will work on AWS infrastructure and contribute to building robust APIs that power enterprise applications.'
  },
  {
    id: 'job-021',
    title: 'Frontend Intern',
    company: 'Glitch',
    location: 'Bengaluru',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['React', 'JavaScript', 'CSS', 'Git'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '₹21k–₹36k/month Internship',
    applyUrl: 'https://glitch.com/careers/intern-001',
    description: 'Glitch is hiring frontend interns to build web experiences. You will work with React and modern frontend tools. This internship offers mentorship, code review feedback, and exposure to startup culture and rapid product development.'
  },
  {
    id: 'job-022',
    title: 'Backend Developer (0-1 years)',
    company: 'Unacademy',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Python', 'Django', 'PostgreSQL', 'Redis'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '5–8 LPA',
    applyUrl: 'https://unacademy.com/careers/backend-001',
    description: 'Unacademy is seeking backend developers to build educational technology. You will develop APIs and services using Python and Django. You will work on features that impact millions of students learning on our platform.'
  },
  {
    id: 'job-023',
    title: 'QA Engineer (3-5 years)',
    company: 'Myntra',
    location: 'Bengaluru',
    mode: 'Onsite',
    experience: '3-5',
    skills: ['Selenium', 'Java', 'API Testing', 'Jenkins'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '10–15 LPA',
    applyUrl: 'https://myntra.com/careers/qa-eng-001',
    description: 'Myntra is hiring experienced QA engineers to ensure product quality at scale. You will design test strategies, automate test cases, and lead quality initiatives. You will work on features affecting millions of daily active users on India\'s leading fashion e-commerce platform.'
  },
  {
    id: 'job-024',
    title: 'Cloud Architect (5+ years)',
    company: 'AWS',
    location: 'Delhi',
    mode: 'Hybrid',
    experience: '5+',
    skills: ['AWS', 'Infrastructure', 'Terraform', 'Python', 'Security'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '25–35 LPA',
    applyUrl: 'https://aws.com/careers/architect-001',
    description: 'AWS is hiring cloud architects to design scalable infrastructure solutions. You will work with enterprise customers to architect cloud solutions. You will lead cloud transformation initiatives and mentor junior architects in building secure, efficient cloud systems.'
  },
  {
    id: 'job-025',
    title: 'React Native Developer (1-3 years)',
    company: 'Urban Company',
    location: 'Gurgaon',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React Native', 'JavaScript', 'Redux', 'Firebase'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '10–15 LPA',
    applyUrl: 'https://urbancompany.com/careers/rn-dev-001',
    description: 'Urban Company is hiring React Native developers to build mobile apps. You will develop cross-platform mobile applications for service booking. You will collaborate with product and design teams to deliver high-performance mobile experiences.'
  },
  {
    id: 'job-026',
    title: 'SDE Intern - Backend',
    company: 'Atlassian',
    location: 'Bengaluru',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['Java', 'Spring Boot', 'SQL', 'Git'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹25k–₹40k/month Internship',
    applyUrl: 'https://atlassian.com/careers/backend-intern-001',
    description: 'Atlassian is hiring backend developer interns to work on developer tools. You will write Java code, participate in code reviews, and learn best practices. This internship provides exposure to building products used by millions of developers globally.'
  },
  {
    id: 'job-027',
    title: 'Product Manager (3-5 years)',
    company: 'Ola',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '3-5',
    skills: ['Product Strategy', 'Data Analysis', 'Leadership', 'SQL'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '16–24 LPA',
    applyUrl: 'https://ola.com/careers/pm-001',
    description: 'Ola is hiring product managers to lead mobility initiatives. You will own product roadmaps, analyze user data, and lead cross-functional teams. You will shape the future of transportation and drive product decisions impacting millions of users.'
  },
  {
    id: 'job-028',
    title: 'Security Engineer (1-3 years)',
    company: 'Fortanix',
    location: 'Bengaluru',
    mode: 'Remote',
    experience: '1-3',
    skills: ['Cryptography', 'C++', 'Rust', 'Security', 'AWS'],
    source: 'Indeed',
    postedDaysAgo: 5,
    salaryRange: '11–16 LPA',
    applyUrl: 'https://fortanix.com/careers/security-001',
    description: 'Fortanix is hiring security engineers to build encryption infrastructure. You will work with Rust and C++, implement cryptographic protocols, and design secure systems. You will contribute to open-source security projects and advance the state of cloud security.'
  },
  {
    id: 'job-029',
    title: 'Full Stack Developer (0-1 years)',
    company: 'Cleartax',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['JavaScript', 'React', 'Node.js', 'MongoDB'],
    source: 'Naukri',
    postedDaysAgo: 2,
    salaryRange: '5–8 LPA',
    applyUrl: 'https://cleartax.com/careers/fullstack-001',
    description: 'Cleartax is hiring junior full stack developers to build tax and financial software. You will work with modern web technologies like React and Node.js. You will contribute to products that simplify tax and compliance for millions of Indians.'
  },
  {
    id: 'job-030',
    title: 'Data Engineer (3-5 years)',
    company: 'DuckDuckGo',
    location: 'Hyderabad',
    mode: 'Remote',
    experience: '3-5',
    skills: ['Spark', 'Python', 'SQL', 'Hadoop', 'AWS'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '14–20 LPA',
    applyUrl: 'https://duckduckgo.com/careers/data-eng-001',
    description: 'DuckDuckGo is hiring data engineers to build data pipelines. You will work with Apache Spark, design ETL workflows, and optimize data processing. You will contribute to privacy-first data infrastructure supporting millions of search queries.'
  },
  {
    id: 'job-031',
    title: 'QA Intern',
    company: 'BigBasket',
    location: 'Bengaluru',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Selenium', 'Python', 'SQL', 'TestNG'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '₹18k–₹30k/month Internship',
    applyUrl: 'https://bigbasket.com/careers/qa-intern-001',
    description: 'BigBasket is hiring QA interns to ensure grocery e-commerce quality. You will write automated tests, execute test cases, and report bugs. This internship offers experience with e-commerce platforms handling millions of daily transactions.'
  },
  {
    id: 'job-032',
    title: 'Java Developer (1-3 years)',
    company: 'Zomato',
    location: 'Gurgaon',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Java', 'Spring', 'Microservices', 'MySQL', 'Kafka'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '11–16 LPA',
    applyUrl: 'https://zomato.com/careers/java-dev-001',
    description: 'Zomato is hiring Java developers to build food delivery infrastructure. You will develop microservices, work with Kafka for messaging, and scale systems. You will contribute to platforms serving millions of food orders across India.'
  },
  {
    id: 'job-033',
    title: 'Frontend Developer (3-5 years)',
    company: 'Meesho',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '3-5',
    skills: ['React', 'JavaScript', 'CSS', 'Redux', 'Next.js'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '13–18 LPA',
    applyUrl: 'https://meesho.com/careers/frontend-001',
    description: 'Meesho is hiring experienced frontend developers to build social commerce. You will develop React applications with performance optimization. You will work on products connecting millions of small business owners and resellers.'
  },
  {
    id: 'job-034',
    title: 'Cloud Engineer (0-1 years)',
    company: 'Google Cloud',
    location: 'Hyderabad',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['GCP', 'Kubernetes', 'Docker', 'Linux', 'Python'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '7–11 LPA',
    applyUrl: 'https://google.com/careers/cloud-eng-001',
    description: 'Google Cloud is hiring junior cloud engineers to support infrastructure. You will work with GCP, Kubernetes, and Docker. You will contribute to cloud platform infrastructure supporting enterprise customers globally.'
  },
  {
    id: 'job-035',
    title: 'Backend Developer (5+ years)',
    company: 'Microsoft',
    location: 'Noida',
    mode: 'Onsite',
    experience: '5+',
    skills: ['.NET', 'C#', 'SQL Server', 'Azure', 'Architecture'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '22–30 LPA',
    applyUrl: 'https://microsoft.com/careers/backend-senior-001',
    description: 'Microsoft is hiring senior backend developers to build enterprise solutions. You will architect scalable systems using .NET and Azure. You will lead technical teams and drive innovation in cloud and enterprise software.'
  },
  {
    id: 'job-036',
    title: 'DevOps Intern',
    company: 'Hashicorp',
    location: 'Bengaluru',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['Docker', 'Kubernetes', 'Linux', 'Terraform', 'Git'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '₹19k–₹33k/month Internship',
    applyUrl: 'https://hashicorp.com/careers/devops-intern-001',
    description: 'Hashicorp is hiring DevOps interns to work on infrastructure tools. You will learn Docker, Kubernetes, and Terraform. You will contribute to tools used by thousands of organizations for infrastructure automation.'
  },
  {
    id: 'job-037',
    title: 'Mobile Developer (1-3 years)',
    company: 'MakeMyTrip',
    location: 'Gurgaon',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Swift', 'Kotlin', 'React Native', 'Firebase'],
    source: 'Naukri',
    postedDaysAgo: 3,
    salaryRange: '9–14 LPA',
    applyUrl: 'https://makemytrip.com/careers/mobile-001',
    description: 'MakeMyTrip is hiring mobile developers to build travel apps. You will develop iOS and Android applications for flight and hotel bookings. You will collaborate with product teams to deliver features for millions of travelers.'
  },
  {
    id: 'job-038',
    title: 'Solutions Architect (3-5 years)',
    company: 'Salesforce',
    location: 'Delhi',
    mode: 'Hybrid',
    experience: '3-5',
    skills: ['Salesforce', 'Architecture', 'SQL', 'Apex', 'Leadership'],
    source: 'LinkedIn',
    postedDaysAgo: 7,
    salaryRange: '16–22 LPA',
    applyUrl: 'https://salesforce.com/careers/architect-001',
    description: 'Salesforce is hiring solutions architects to design CRM solutions. You will work with enterprise clients to understand requirements and design architectures. You will lead implementation teams and drive customer success on Salesforce platforms.'
  },
  {
    id: 'job-039',
    title: 'SRE (Site Reliability Engineer) (1-3 years)',
    company: 'Stripe',
    location: 'Bengaluru',
    mode: 'Remote',
    experience: '1-3',
    skills: ['Go', 'Python', 'Kubernetes', 'Monitoring', 'AWS'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '12–18 LPA',
    applyUrl: 'https://stripe.com/careers/sre-001',
    description: 'Stripe is hiring Site Reliability Engineers to ensure payment platform stability. You will build monitoring and observability systems, manage deployments, and optimize infrastructure. You will work on systems processing billions in payments globally.'
  },
  {
    id: 'job-040',
    title: 'ML Engineer Intern',
    company: 'OpenAI',
    location: 'Remote',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['Python', 'PyTorch', 'Deep Learning', 'Linear Algebra'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '₹26k–₹42k/month Internship',
    applyUrl: 'https://openai.com/careers/ml-intern-001',
    description: 'OpenAI is hiring ML engineer interns to work on AI research and products. You will implement deep learning models, run experiments, and contribute to AI advancement. This is a unique opportunity to work on cutting-edge AI technology.'
  },
  {
    id: 'job-041',
    title: 'Backend Developer (3-5 years)',
    company: 'Instamojo',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '3-5',
    skills: ['Python', 'Django', 'PostgreSQL', 'Redis', 'AWS'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '12–17 LPA',
    applyUrl: 'https://instamojo.com/careers/backend-001',
    description: 'Instamojo is hiring backend developers to build payment infrastructure. You will develop APIs for payment processing, work with high volume transaction data, and optimize system performance. You will contribute to fintech products simplifying payments for Indians.'
  },
  {
    id: 'job-042',
    title: 'Frontend Developer (0-1 years)',
    company: 'Dunzo',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['React', 'JavaScript', 'CSS', 'Redux'],
    source: 'Indeed',
    postedDaysAgo: 5,
    salaryRange: '5–8 LPA',
    applyUrl: 'https://dunzo.com/careers/frontend-001',
    description: 'Dunzo is hiring junior frontend developers to build quick commerce experiences. You will develop React interfaces for same-day delivery. You will work on user experience improvements for millions of customers.'
  },
  {
    id: 'job-043',
    title: 'Backend Engineer (5+ years)',
    company: 'Coinbase',
    location: 'Bengaluru',
    mode: 'Remote',
    experience: '5+',
    skills: ['Go', 'Rust', 'Postgres', 'AWS', 'Architecture'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '24–32 LPA',
    applyUrl: 'https://coinbase.com/careers/backend-senior-001',
    description: 'Coinbase is hiring senior backend engineers to build crypto infrastructure. You will design systems handling millions of transactions, work with blockchain technology, and lead technical initiatives. You will contribute to crypto finance innovation globally.'
  },
  {
    id: 'job-044',
    title: 'QA Engineer (0-1 years)',
    company: 'Atlassian',
    location: 'Hyderabad',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Selenium', 'Java', 'SQL', 'Git', 'JIRA'],
    source: 'Naukri',
    postedDaysAgo: 1,
    salaryRange: '5–8 LPA',
    applyUrl: 'https://atlassian.com/careers/qa-eng-001',
    description: 'Atlassian is hiring junior QA engineers to test developer tools. You will write automated tests, identify bugs, and contribute to quality. You will work on products used by millions of developers and teams worldwide.'
  },
  {
    id: 'job-045',
    title: 'Database Administrator (1-3 years)',
    company: 'Hasura',
    location: 'Bengaluru',
    mode: 'Remote',
    experience: '1-3',
    skills: ['PostgreSQL', 'MongoDB', 'Optimization', 'Monitoring'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '9–14 LPA',
    applyUrl: 'https://hasura.com/careers/dba-001',
    description: 'Hasura is hiring database administrators to optimize data systems. You will manage PostgreSQL and MongoDB clusters, optimize queries, and ensure reliability. You will contribute to data infrastructure for thousands of applications.'
  },
  {
    id: 'job-046',
    title: 'Frontend Intern',
    company: 'Vercel',
    location: 'Remote',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['React', 'Next.js', 'JavaScript', 'CSS'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '₹20k–₹35k/month Internship',
    applyUrl: 'https://vercel.com/careers/frontend-intern-001',
    description: 'Vercel is hiring frontend interns to work on deployment platform UI. You will develop Next.js applications, contribute to open source, and learn modern web development. You will work on products enabling millions of web deployments.'
  },
  {
    id: 'job-047',
    title: 'Backend Developer (1-3 years)',
    company: 'Gupshup',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Java', 'Spring Boot', 'Kafka', 'MySQL', 'AWS'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '8–12 LPA',
    applyUrl: 'https://gupshup.com/careers/backend-001',
    description: 'Gupshup is hiring backend developers to build messaging infrastructure. You will develop APIs for SMS and WhatsApp messaging at scale. You will work on platforms enabling businesses to reach billions of customers globally.'
  },
  {
    id: 'job-048',
    title: 'Product Designer (3-5 years)',
    company: 'Figma',
    location: 'Remote',
    mode: 'Remote',
    experience: '3-5',
    skills: ['UI Design', 'User Research', 'Prototyping', 'Design Systems'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '18–26 LPA',
    applyUrl: 'https://figma.com/careers/designer-001',
    description: 'Figma is hiring product designers to shape design tools. You will lead design initiatives, conduct user research, and build design systems. You will contribute to tools used by millions of designers worldwide.'
  },
  {
    id: 'job-049',
    title: 'Android Developer (0-1 years)',
    company: 'Grab',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Kotlin', 'Android', 'Java', 'Firebase'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '6–9 LPA',
    applyUrl: 'https://grab.com/careers/android-001',
    description: 'Grab is hiring junior Android developers to build Southeast Asian app ecosystem. You will develop Kotlin apps for ride-hailing and delivery. You will contribute to services serving millions of users across Southeast Asia.'
  },
  {
    id: 'job-050',
    title: 'Senior DevOps Engineer (5+ years)',
    company: 'GitLab',
    location: 'Remote',
    mode: 'Remote',
    experience: '5+',
    skills: ['Kubernetes', 'Go', 'GCP', 'GitOps', 'Security'],
    source: 'LinkedIn',
    postedDaysAgo: 7,
    salaryRange: '26–34 LPA',
    applyUrl: 'https://gitlab.com/careers/devops-senior-001',
    description: 'GitLab is hiring senior DevOps engineers to manage platform infrastructure. You will lead infrastructure initiatives, design HA systems, and mentor teams. You will contribute to DevOps platform infrastructure for millions globally.'
  },
  {
    id: 'job-051',
    title: 'Graduate Trainee',
    company: 'Google',
    location: 'Hyderabad',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['C++', 'Java', 'Python', 'Data Structures', 'Algorithms'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '4–6 LPA',
    applyUrl: 'https://google.com/careers/trainee-001',
    description: 'Google is hiring graduate trainees through structured program. You will work on real Google products, receive mentorship, and build foundational skills. This program offers exposure to innovative technology and scale at Google.'
  },
  {
    id: 'job-052',
    title: 'Data Scientist (1-3 years)',
    company: 'Byju\'s',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Python', 'Machine Learning', 'SQL', 'Statistics', 'Tableau'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '10–15 LPA',
    applyUrl: 'https://byju.com/careers/datascience-001',
    description: 'Byju\'s is hiring data scientists to improve learning experiences. You will build ML models for personalized learning, analyze educational data, and drive product insights. You will contribute to AI-powered education affecting millions of students.'
  },
  {
    id: 'job-053',
    title: 'Full Stack Developer (3-5 years)',
    company: 'Mindtickle',
    location: 'Pune',
    mode: 'Hybrid',
    experience: '3-5',
    skills: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'AWS'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '14–20 LPA',
    applyUrl: 'https://mindtickle.com/careers/fullstack-001',
    description: 'Mindtickle is hiring full stack developers to build sales enablement platform. You will develop React and Node.js features, optimize performance, and scale systems. You will contribute to platforms used by Fortune 500 companies.'
  },
  {
    id: 'job-054',
    title: 'iOS Developer (1-3 years)',
    company: 'Dream11',
    location: 'Bengaluru',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Swift', 'iOS', 'Objective-C', 'Firebase'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '11–16 LPA',
    applyUrl: 'https://dream11.com/careers/ios-dev-001',
    description: 'Dream11 is hiring iOS developers to build fantasy sports app. You will develop Swift apps, optimize performance, and work with real-time data. You will contribute to apps used by millions of sports enthusiasts in India.'
  },
  {
    id: 'job-055',
    title: 'Backend Developer (0-1 years)',
    company: 'Vedantu',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Node.js', 'JavaScript', 'MongoDB', 'Express', 'AWS'],
    source: 'Naukri',
    postedDaysAgo: 1,
    salaryRange: '5–8 LPA',
    applyUrl: 'https://vedantu.com/careers/backend-001',
    description: 'Vedantu is hiring junior backend developers to build online learning platform. You will develop Node.js APIs, work with real-time communication, and scale services. You will contribute to education technology impacting millions of learners.'
  },
  {
    id: 'job-056',
    title: 'QA Automation Engineer (3-5 years)',
    company: 'Thoughtworks',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '3-5',
    skills: ['Selenium', 'Java', 'TestNG', 'CI/CD', 'BDD'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '13–18 LPA',
    applyUrl: 'https://thoughtworks.com/careers/qa-automation-001',
    description: 'Thoughtworks is hiring QA automation engineers to drive quality practices. You will build test automation frameworks, implement BDD, and mentor teams. You will contribute to quality assurance for global enterprise projects.'
  },
  {
    id: 'job-057',
    title: 'React Developer (1-3 years)',
    company: 'Delhivery',
    location: 'Gurgaon',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'JavaScript', 'Redux', 'CSS', 'Node.js'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '9–14 LPA',
    applyUrl: 'https://delhivery.com/careers/react-dev-001',
    description: 'Delhivery is hiring React developers to build logistics platform. You will develop React dashboards, optimize performance, and collaborate with backend teams. You will contribute to logistics technology serving millions of shipments.'
  },
  {
    id: 'job-058',
    title: 'Backend Engineer (3-5 years)',
    company: 'Zeta',
    location: 'Bengaluru',
    mode: 'Hybrid',
    experience: '3-5',
    skills: ['Scala', 'Kafka', 'Microservices', 'AWS', 'PostgreSQL'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '14–20 LPA',
    applyUrl: 'https://zeta.tech/careers/backend-001',
    description: 'Zeta is hiring backend engineers to build fintech infrastructure. You will develop Scala microservices, handle high-throughput data, and ensure reliability. You will contribute to financial technology serving millions of transactions.'
  },
  {
    id: 'job-059',
    title: 'UX Designer (0-1 years)',
    company: 'Ixigo',
    location: 'Gurgaon',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Figma', 'User Research', 'Prototyping', 'HTML/CSS'],
    source: 'Naukri',
    postedDaysAgo: 3,
    salaryRange: '5–8 LPA',
    applyUrl: 'https://ixigo.com/careers/designer-001',
    description: 'Ixigo is hiring junior UX designers to improve travel experiences. You will design interfaces, conduct user research, and iterate on feedback. You will contribute to travel platform helping millions of Indians plan trips.'
  },
  {
    id: 'job-060',
    title: 'Senior Backend Developer (5+ years)',
    company: 'Elastic',
    location: 'Remote',
    mode: 'Remote',
    experience: '5+',
    skills: ['Java', 'Elasticsearch', 'Distributed Systems', 'Architecture'],
    source: 'LinkedIn',
    postedDaysAgo: 7,
    salaryRange: '28–36 LPA',
    applyUrl: 'https://elastic.com/careers/backend-senior-001',
    description: 'Elastic is hiring senior backend developers to build search and observability platform. You will architect distributed systems, optimize performance, and lead technical initiatives. You will contribute to platforms used by millions of developers globally.'
  }
];
